/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Model.Controller;
import Model.Tutor;
import Model.Tutorado;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;

/**
 *
 * @author ambro
 * 
 */
public final class ITutorado extends javax.swing.JFrame {
    final private Controller control;
    
    //Asignar tutorado 
    private Tutor tutor;
    private Tutorado tutorado;
    private List<Tutorado>tutorados;
    private List<Tutor> tutores;

    private DefaultListModel modelEst;
    private DefaultListModel modelTutorados;
    
    private Map<String, Tutorado> tutoradoMap=new HashMap<>();
    private final String SELECCIONA= "Selecciona un tutor";
    private final String SELECCIONADO= "Tutor seleccionado";
    
    //Crear tutorado
    private Tutorado tutN;
    
    
    /**
     * Creates new form ITutorado
     */
    public ITutorado() {
        initComponents();
        control = new Controller();

        
        cargarTutores();
        cargarEstudiantes();
        cargarNoControl();
        listEst.setModel(modelEst);
        listTutorados.setModel(modelTutorados);
        
        listEst.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        listTutorados.setSelectionMode(2);
        
        
        btnAñadirTutorado.setEnabled(false);
    pack();
    setLocationRelativeTo(null);
    }
    
    
    public void cargarTutores(){
        tutores= control.traerTutores();
        cmbTutor.removeAllItems();
        cmbTutor.addItem("Selecciona un tutor");
        for(Tutor dTutor: tutores){
            cmbTutor.addItem(dTutor.getNombre());
        }
      
    }
    
    public void cargarEstudiantes(){
        tutorados= control.traerTutorado();
        modelEst= new DefaultListModel();
        modelTutorados= new DefaultListModel();
        modelEst.clear();
        
        for(Tutorado t: tutorados){
            if(t.getTutorId()==null){
                modelEst.addElement(t.getNombre());
                tutoradoMap.put(t.getNombre(), t);
            }
        }
    }
    
    public void cargarNoControl(){
        String ncTutorado="";
        List <Tutorado> tut2= control.traerTutorado();
        if (!tut2.isEmpty()) {
            ncTutorado = tut2.get(tut2.size() - 1).getNoControl(); // último
        } else {
            ncTutorado = "200000"; // valor inicial si no hay registros
        }
        System.out.println(ncTutorado);
        int noControlN= Integer.parseInt(ncTutorado);
        noControlN++;
        
        cmbNoControl.removeAllItems();
        cmbNoControl.addItem(""+noControlN);
        cmbNoControl.setSelectedIndex(0);
        cmbNoControl.setEditable(true);
    }
    
    public void repiteProceso(){
        btnAñadirTutorado.setEnabled(false);
        cmbTutor.setEnabled(true);
        btnAñadir.setText(SELECCIONA);
        btnAñadir.setEnabled(true);
        
        cargarTutores();
        cargarEstudiantes();
        
        listEst.setModel(modelEst);
        listTutorados.setModel(modelTutorados);
        jCNacimiento.setDate(new Date());
        
    }
    
    public void limpiarRegistrar(){
        txtNombre.setText("");
        bttSexo.clearSelection();
        cargarNoControl();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttSexo = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbCarrera = new javax.swing.JLabel();
        cmbNoControl = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JFormattedTextField();
        lbNombre = new javax.swing.JLabel();
        rbtnM = new javax.swing.JRadioButton();
        rbtnF = new javax.swing.JRadioButton();
        lbCarrera1 = new javax.swing.JLabel();
        lbCarrera2 = new javax.swing.JLabel();
        jCNacimiento = new de.wannawork.jcalendar.JCalendarComboBox();
        btnAceptar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmbTutor = new javax.swing.JComboBox<>();
        lbSeleccionaTutor = new javax.swing.JLabel();
        lblSelecciona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTutorados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEst = new javax.swing.JList<>();
        btnAñadirTutorado = new javax.swing.JButton();
        btnQuitarTutorado = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblSelecciona1 = new javax.swing.JLabel();
        lblSelecciona2 = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCarrera.setText("No. Cotrol:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        lbNombre.setText("Nombre completo:");

        bttSexo.add(rbtnM);
        rbtnM.setText("M");
        rbtnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMActionPerformed(evt);
            }
        });

        bttSexo.add(rbtnF);
        rbtnF.setSelected(true);
        rbtnF.setText("F");

        lbCarrera1.setText("Genero:");

        lbCarrera2.setText("Fecha Nacimiento:");

        btnAceptar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar1.setText("Aceptar");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNombre)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbCarrera)
                                .addComponent(lbCarrera1)
                                .addComponent(lbCarrera2)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(rbtnM, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(rbtnF, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAceptar1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCarrera)
                            .addComponent(cmbNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnM)
                            .addComponent(rbtnF)
                            .addComponent(lbCarrera1))
                        .addGap(49, 49, 49)
                        .addComponent(lbCarrera2))
                    .addComponent(jCNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnAceptar1)
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Registrar tutorados", jPanel2);

        cmbTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbSeleccionaTutor.setText("Selecciona un tutor:");

        lblSelecciona.setText("Selección de tutorado:");

        listTutorados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listTutorados);

        listEst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEst);

        btnAñadirTutorado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadirTutorado.setText("=>");
        btnAñadirTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTutoradoActionPerformed(evt);
                btnAñadirTutoradoActionPerformed1(evt);
                btnAñadirTutoradoActionPerformed2(evt);
            }
        });

        btnQuitarTutorado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarTutorado.setText("<=");
        btnQuitarTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarTutoradoActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblSelecciona1.setText("Seleccionar estudiantes:");

        lblSelecciona2.setText("Tutorados:");

        btnAñadir.setText("Aceptar tutor");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAñadirTutorado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitarTutorado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSelecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(lblSelecciona2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSeleccionaTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSelecciona1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeleccionaTutor)
                    .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAñadir)
                .addGap(34, 34, 34)
                .addComponent(lblSelecciona)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelecciona1)
                            .addComponent(lblSelecciona2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAñadirTutorado)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarTutorado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(59, 59, 59))))
        );

        jTabbedPane1.addTab("Asignar tutor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed

    private void btnQuitarTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarTutoradoActionPerformed
        int[] indEstSelect= listTutorados.getSelectedIndices();
        for(int i= indEstSelect.length-1; i>=0; i--){
            modelEst.addElement(modelTutorados.get(indEstSelect[i]));
            modelTutorados.remove(indEstSelect[i]);
        }
        
    }//GEN-LAST:event_btnQuitarTutoradoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        for(int i=0; i<modelTutorados.size();i++){
            String nombre= (String)modelTutorados.get(i);
            Tutorado t = tutoradoMap.get(nombre);
            if(t!=null){
                t.setTutorId(tutor);
                try {
                    control.editarTutorado(t);
                } catch (Exception ex) {
                    Logger.getLogger(ITutorado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        JOptionPane.showMessageDialog(this,"Tutor asignado correctamente");
        repiteProceso();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        if(cmbTutor.getSelectedItem().equals(SELECCIONA))
            JOptionPane.showMessageDialog(this,"Selecciona un tutor");
        else
            if(JOptionPane.showConfirmDialog(this, "Seleccionaste al tutor"+cmbTutor.getSelectedItem()+"?")==0){
                tutor= tutores.get(cmbTutor.getSelectedIndex()-1);
                cmbTutor.setEnabled(false);
                btnAñadir.setText(SELECCIONADO);
                btnAñadir.setEnabled(false);
                
                if(!modelEst.isEmpty()){
                    btnAñadirTutorado.setEnabled(true);
                }
            }
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnAñadirTutoradoActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed1
        
        
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed1

    private void btnAñadirTutoradoActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed2
        int[] indEstSelect= listEst.getSelectedIndices();
        for(int i= indEstSelect.length-1; i>=0; i--){
            modelTutorados.addElement(modelEst.get(indEstSelect[i]));
            modelEst.remove(indEstSelect[i]);
        }
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed2

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void rbtnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMActionPerformed

    
    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        
        java.util.Date utilDate = jCNacimiento.getDate();
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        
        int n= cmbNoControl.getSelectedIndex();
        ComboBoxModel<String> model = cmbNoControl.getModel();
          
        tutN= new Tutorado();
        tutN.setFecha(sqlDate);
        tutN.setNombre(txtNombre.getText());
        tutN.setGenero(rbtnM.isSelected()?'M':'F');
        tutN.setNoControl((String)model.getSelectedItem());
        
        try {
            control.crearTutorado(tutN);
            JOptionPane.showMessageDialog(this,"Tutorado agregado correctamente");
            repiteProceso();
            limpiarRegistrar();
            
        } catch (Exception ex) {
            Logger.getLogger(ITutorado.class.getName()).log(Level.SEVERE, null, ex);}
        
    }//GEN-LAST:event_btnAceptar1ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITutorado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnAñadirTutorado;
    private javax.swing.JButton btnQuitarTutorado;
    private javax.swing.ButtonGroup bttSexo;
    private javax.swing.JComboBox<String> cmbNoControl;
    private javax.swing.JComboBox<String> cmbTutor;
    private de.wannawork.jcalendar.JCalendarComboBox jCNacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCarrera;
    private javax.swing.JLabel lbCarrera1;
    private javax.swing.JLabel lbCarrera2;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbSeleccionaTutor;
    private javax.swing.JLabel lblSelecciona;
    private javax.swing.JLabel lblSelecciona1;
    private javax.swing.JLabel lblSelecciona2;
    private javax.swing.JList<String> listEst;
    private javax.swing.JList<String> listTutorados;
    private javax.swing.JRadioButton rbtnF;
    private javax.swing.JRadioButton rbtnM;
    private javax.swing.JFormattedTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
