/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Controller;
import Modelo.Tutor;
import Modelo.Tutorado;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;
import javax.swing.UIManager;

/**
 *
 * @author ambro
 */
public class ITutorado extends javax.swing.JFrame {
    private Controller control;
    private Tutor tutor;
    private Tutorado tutorado;
    private List<Tutorado>tutorados;
    private List<Tutor> tutores;
    
    private DefaultListModel modelEst;
    private DefaultListModel modelTutorados;
    
    
    /**
     * Creates new form ITutorado
     */
    public ITutorado() {
        initComponents();
        control = new Controller();
        tutores= control.traerTutores();
        tutorados= control.traerTutorado();
        cargarTutores();
        cargarEstudiantes();
        
        listEst.setModel(modelEst);
        listEst.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        listTutorados.setModel(modelTutorados);
        
    pack();
    setLocationRelativeTo(null);
    }
    
    
    public void cargarTutores(){
        cmbTutor.removeAllItems();
        cmbTutor.addItem("Selecciona un tutor");
        for(Tutor dTutor: tutores){
            cmbTutor.addItem(dTutor.getNombre());
        }
      
    }
    
    public void cargarEstudiantes(){
        modelEst= new DefaultListModel();
        modelTutorados= new DefaultListModel();
        modelEst.clear();
        
        for(Tutorado t: tutorados){
            if(t.getTutorId()==null)
                modelEst.addElement(t.getNombre());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        cmbTutor = new javax.swing.JComboBox<>();
        lbSeleccionaTutor = new javax.swing.JLabel();
        lblSelecciona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTutorados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEst = new javax.swing.JList<>();
        btnAñadirTutorado = new javax.swing.JButton();
        btnQuitarTutorado = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        lblSelecciona1 = new javax.swing.JLabel();
        lblSelecciona2 = new javax.swing.JLabel();
        btnAñadirTutorado1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Registrar tutorados", jPanel2);

        cmbTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbSeleccionaTutor.setText("Selecciona un tutor:");

        lblSelecciona.setText("Selección de tutorado:");

        listTutorados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listTutorados);

        listEst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEst);

        btnAñadirTutorado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAñadirTutorado.setText("=>");
        btnAñadirTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTutoradoActionPerformed(evt);
                btnAñadirTutoradoActionPerformed1(evt);
                btnAñadirTutoradoActionPerformed2(evt);
            }
        });

        btnQuitarTutorado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuitarTutorado.setText("<=");
        btnQuitarTutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarTutoradoActionPerformed(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblSelecciona1.setText("Seleccionar estudiantes:");

        lblSelecciona2.setText("Tutorados:");

        btnAñadirTutorado1.setText("Aceptar tutor");
        btnAñadirTutorado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirTutorado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnAñadirTutorado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitarTutorado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSelecciona, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(lblSelecciona2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAñadirTutorado1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbSeleccionaTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSelecciona1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSeleccionaTutor)
                    .addComponent(cmbTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAñadirTutorado1)
                .addGap(34, 34, 34)
                .addComponent(lblSelecciona)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelecciona1)
                            .addComponent(lblSelecciona2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnAñadirTutorado)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitarTutorado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(59, 59, 59))))
        );

        jTabbedPane1.addTab("Asignar tutor", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed

    private void btnQuitarTutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarTutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarTutoradoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAñadirTutorado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutorado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirTutorado1ActionPerformed

    private void btnAñadirTutoradoActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed1
        
        
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed1

    private void btnAñadirTutoradoActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirTutoradoActionPerformed2
        int[] indEstSelect= listEst.getSelectedIndices();
        for(int i= indEstSelect.length-1; i>=0; i--){
            modelTutorados.addElement(modelEst.get(indEstSelect[i]));
            modelEst.remove(indEstSelect[i]);
        }
    }//GEN-LAST:event_btnAñadirTutoradoActionPerformed2

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITutorado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAñadirTutorado;
    private javax.swing.JButton btnAñadirTutorado1;
    private javax.swing.JButton btnQuitarTutorado;
    private javax.swing.JComboBox<String> cmbTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbSeleccionaTutor;
    private javax.swing.JLabel lblSelecciona;
    private javax.swing.JLabel lblSelecciona1;
    private javax.swing.JLabel lblSelecciona2;
    private javax.swing.JList<String> listEst;
    private javax.swing.JList<String> listTutorados;
    // End of variables declaration//GEN-END:variables
}
